{% set version = "1.4.1" %}
{% set python_min = "3.10" %}

package:
  name: dinosaur-dycore
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/d/dinosaur/dinosaur-{{ version }}.tar.gz
  sha256: 6115f6512685e60860996ab4db1c94c3f67128d931ec8b0cdf3ab19dca5d23ad

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - jax
    - jaxlib
    - numpy
    - pint
    - scipy
    - scikit-learn
    - tree-math
    - dask-core
    - fsspec
    - pandas
    - xarray
    - xarray-tensorstore

test:
  imports:
    - dinosaur
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/google-research/dinosaur
  summary: differentiable dynamics for global atmospheric modeling
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
