{% set version = "1.3.2" %}
{% set python_min = "3.10" %}

package:
  name: dinosaur-dycore
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/d/dinosaur/dinosaur-{{ version }}.tar.gz
  sha256: 15a72192c19ad7c9a2ca0d5e2100b2e1abef2ca5416bb9b09d06bb84613521f0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - jax
    - jaxlib
    - numpy
    - pint
    - scipy
    - scikit-learn
    - tree-math
    - dask-core
    - fsspec
    - pandas
    - xarray
    - xarray-tensorstore

test:
  imports:
    - dinosaur
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/google-research/dinosaur
  summary: differentiable dynamics for global atmospheric modeling
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
