{% set name = "dinosaur-dycore" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dinosaur_dycore-{{ version }}.tar.gz
  sha256: bd73146cd4994f955b6c76e27a82a287b6ee3d52db339734fee94bdfa7ba2d28

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools
    - pip
  run:
    - python >=3.10
    - fsspec
    - jax
    - jaxlib
    - numpy
    - pandas
    - pint
    - scipy
    - scikit-learn
    - tree-math
    - xarray
    - xarray-tensorstore

test:
  imports:
    - dinosaur
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/google-research/dinosaur
  summary: differentiable dynamics for global atmospheric modeling
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
